// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 moved the seed command here from package.json's `prisma.seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations + introspection use DATABASE_URL. In MVP this points at
    // Supabase's Session pooler (port 5432). At Vercel deploy we'll swap
    // the runtime connection to a Prisma driver adapter targeting the
    // Transaction pooler (port 6543) and leave migrations on Session —
    // Prisma 7 removed the schema-level `directUrl` field, so the
    // migration/runtime split now lives in the PrismaClient constructor.
    // See docs/DECISIONS.md.
    url: process.env["DATABASE_URL"],
  },
});
